/*
 * COPYRIGHT. HSBC HOLDINGS PLC 2018. ALL RIGHTS RESERVED.
 *
 * This software is only to be used for the purpose for which it has been
 * provided. No part of it is to be reproduced, disassembled, transmitted,
 * stored in a retrieval system nor translated in any human or computer
 * language in any way or for any other purposes whatsoever without the
 * prior written consent of HSBC Holdings plc.
 */
package com.hsbc.hbar.filerepo.model.enums;

public enum MdwEnum {
	// WS
	WS_GET_ACCESS_TOKEN_BY_TYPE("wsGetAccessTokenByType"),
	WS_RETRIEVE_CREDENTIAL_DETAILS("wsRetrieveCredentialDetails"),
	WS_GENERATE_PDF_REPORT_TEXTO("wsGeneratePdfReportTexto"),
	WS_SEND_PDF_REPORT("wsSendPdfReport"),
	// SP
	SP_PAROV_TIPOSDOC("P_PAROV_TIPOSDOC"),
	SP_FR_PAR_TIPODOC_SEL("FR_PAR_TIPODOC_SEL"),
	SP_FR_PAR_TIPODOC_IUP("FR_PAR_TIPODOC_IUP"),
	SP_FR_PAR_GRUPODOC_SEL("FR_PAR_GRUPODOC_SEL"),
	SP_FR_PAR_PERFIL_SEL("FR_PAR_PERFIL_SEL"),
	SP_FR_PAR_PERFIL_IUP("FR_PAR_PERFIL_IUP"),
	SP_FR_PAR_FASE_SEL("FR_PAR_FASE_SEL"),
	SP_FR_PAR_ESTADO_SEL("FR_PAR_ESTADO_SEL"),
	SP_FR_PAR_PERMISO_SEL("FR_PAR_PERMISO_SEL"),
	SP_FR_PAR_PENMOT_SEL("FR_PAR_PENMOT_SEL"),
	SP_FR_PAR_ALEXFAS_SEL("FR_PAR_ALEXFAS_SEL"),
	SP_FR_PAR_ALEXFAS_IUP("FR_PAR_ALEXFAS_IUP"),
	SP_FR_PAR_ALEXEST_SEL("FR_PAR_ALEXEST_SEL"),
	SP_FR_OPE_SOLICITUD_SEL("FR_OPE_SOLICITUD_SEL"),
	SP_FR_OPE_SOLICITUD_FIL("FR_OPE_SOLICITUD_FIL"),
	SP_FR_OPE_SOLICITUD_BTC("FR_OPE_SOLICITUD_BTC"),
	SP_FR_OPE_SOLICITUD_UPD("FR_OPE_SOLICITUD_UPD"),
	SP_FR_OPE_SOLICITUD_TSO("FR_OPE_SOLICITUD_TSO"),
	SP_FR_OPE_SOLIVERIF_INS("FR_OPE_SOLIVERIF_INS"),
	SP_FR_OPE_SOLIC_EST_VER("FR_OPE_SOLIC_EST_VER"),
	SP_FR_OPE_ARCXSOL_SEL("FR_OPE_ARCXSOL_SEL"),
	SP_FR_OPE_ARCXSOL_FIL("FR_OPE_ARCXSOL_FIL"),
	SP_FR_OPE_ARCXSOL_INS("FR_OPE_ARCXSOL_INS"),
	SP_FR_OPE_ARCXSOL_DEL("FR_OPE_ARCXSOL_DEL"),
	SP_FR_OPE_ARCHIVO_SEL("FR_OPE_ARCHIVO_SEL"),
	SP_FR_HIS_SOLICITUD_SEL("FR_HIS_SOLICITUD_SEL"),
	SP_FR_BTC_LOGPROC_SEL("FR_BTC_LOGPROC_SEL"),
	SP_FR_BTC_LOGPROC_INS("FR_BTC_LOGPROC_INS"),
	SP_FR_OPE_SOLICKL_SEL("FR_OPE_SOLICKL_SEL"),
	SP_FR_OPE_SOLICKL_UPD("FR_OPE_SOLICKL_UPD"),
	SP_FR_OPE_SINIESTRO_SEL("FR_OPE_SINIESTRO_SEL"),
	SP_FR_OPE_SINIESTRO_FIL("FR_OPE_SINIESTRO_FIL"),
	SP_FR_OPE_SINIESTRO_UPD("FR_OPE_SINIESTRO_UPD"),
	SP_FR_OPE_ARCXSIN_INS("FR_OPE_ARCXSIN_INS"),
	SP_FR_OPE_ARCXSIN_UPD("FR_OPE_ARCXSIN_UPD"),
	SP_FR_OPE_ARCXSIN_DEL("FR_OPE_ARCXSIN_DEL"),
	SP_FR_OPE_ARCXSIN_SEL("FR_OPE_ARCXSIN_SEL"),
	SP_FR_OPE_ARCXSIN_FIL("FR_OPE_ARCXSIN_FIL"),
	SP_FR_OPE_SINARCH_SEL("FR_OPE_SINARCH_SEL"),
	SP_FR_OPE_BENEFIC_SEL("FR_OPE_BENEFIC_SEL"),
	SP_FR_OPE_BENEFIC_FIL("FR_OPE_BENEFIC_FIL"),
	SP_FR_OPE_BENEFIC_UPD("FR_OPE_BENEFIC_UPD"),
	SP_FR_OPE_ARCXBEN_INS("FR_OPE_ARCXBEN_INS"),
	SP_FR_OPE_ARCXBEN_DEL("FR_OPE_ARCXBEN_DEL"),
	SP_FR_OPE_ARCXBEN_SEL("FR_OPE_ARCXBEN_SEL"),
	SP_FR_OPE_BENARCH_SEL("FR_OPE_BENARCH_SEL"),
	SP_FR_OPE_RETCOL_SEL("FR_OPE_RETCOL_SEL"),
	SP_FR_OPE_RETCOL_FIL("FR_OPE_RETCOL_FIL"),
	SP_FR_OPE_RETCOL_UPD("FR_OPE_RETCOL_UPD"),
	SP_FR_OPE_ARCXRCO_INS("FR_OPE_ARCXRCO_INS"),
	SP_FR_OPE_ARCXRCO_DEL("FR_OPE_ARCXRCO_DEL"),
	SP_FR_OPE_ARCXRCO_SEL("FR_OPE_ARCXRCO_SEL"),
	SP_FR_OPE_RCOARCH_SEL("FR_OPE_RCOARCH_SEL"),
	P_NBWS_PAR_TPRODVC_SEL("P_NBWS_PAR_TPRODVC_SEL"),
	OV_OPERACION_RET_SEL("OV_OPERACION_RET_SEL"),
	// MQ
	MQ_1111_MOTIVOS_OP_PENDIENTES("1111_MotivosOpPendientes"),
	MQ_1161_SOLICITUD_ESTADO("1161_SolicitudEstado");

	private String name;

	private MdwEnum(final String name) {
		this.name = name;
	}

	public String getName() {
		return this.name;
	}
}
