{{ if .Values.release.deploy }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_name }}
  namespace: {{ .Values.release.namespace }}
spec:
  selector:
    app: {{ .Values.app_name }}
  ports:
    - name: service-port
      protocol: TCP
      port: {{ .Values.release.apiServicePort }}
      targetPort: {{ .Values.release.apiContainerPort }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app_name }}
  namespace: {{ .Values.release.namespace }}
spec:
  replicas: {{ .Values.release.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app_name }}
      annotations:
        app: {{ .Values.app_name }}
    spec:
      containers:
      - name: {{ .Values.app_name }}
        image: {{ .Values.release.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.release.apiContainerPort }}
        env:
          - name: NODE_ENV
            value: {{ .Values.release.namespace }}
          {{- range $key, $value := .Values.release.envvars }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
        envFrom:
          - secretRef:
                name: {{ .Values.app_name }}
                optional: true
        livenessProbe:
          httpGet:
            path: /{{ .Values.app_name }}/health
            port: {{ .Values.release.apiContainerPort }}
            scheme: HTTP
          timeoutSeconds: 10
          initialDelaySeconds: 10
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /{{ .Values.app_name }}/health
            port: {{ .Values.release.apiContainerPort }}
            scheme: HTTP
          timeoutSeconds: 10
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 1
---
apiVersion: v1
data:
  APPDYNAMICS_AGENT_TIER_NAME: {{ .Values.app_name }}
kind: ConfigMap
metadata:
  name: {{ .Values.app_name }}-appdynamics-config
  namespace: {{.Values.release.namespace}}
{{ end }}

