name: dotnet build

on:
  workflow_call:  
    inputs:
      dotnet-version:
        description: Dotnet version
        default: "8"
        type: string
        required: false

jobs:
  build:
    runs-on: self-hosted

    steps:
     - name: Dump GitHub context
       env:
         GITHUB_CONTEXT: ${{ toJson(github) }}
       run: echo "$GITHUB_CONTEXT"
       
     - uses: actions/checkout@v4

     - name: Dump 
       run: |
            echo "FEED = ${{ vars.FEED_GS_REPOSITORY }}"
            echo "PAT = ${{ secrets.PAT_GS_REPOSITORY }}"
            
     - name: Setup dotnet ${{ inputs.dotnet-version }}
       uses: actions/setup-dotnet@v4
       with:
         dotnet-version: ${{ inputs.dotnet-version }}
         source-url: ${{ vars.FEED_GS_REPOSITORY }}
       env:
         NUGET_AUTH_TOKEN: ${{secrets.PAT_GS_REPOSITORY}}
         
     - name: Display dotnet version
       run: dotnet --version
       
     - name: Publish
       run: dotnet publish -c release --property:PublishDir=publish
     
     