name: Maven CI/CD

on:
  push:
    branches: [ master ]
    paths:
      - gs-gmas-in-main/settings.xml
      - gs-gmas-in-main/BancaSeguros/**/*

defaults:
 run:
  working-directory: ./gs-gmas-in-main/BancaSeguros/BancaSeguros-Parent

env:
  artifact_version: 1.0.0-SNAPSHOT

jobs:
  build_and_test:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            gs-gmas-in-main/BancaSeguros

      - uses: cschleiden/replace-tokens@v1
        with:
          files: |
            '**/settings.xml'
            '**/pom.xml'
        env:
          PATPKG: ${{secrets.PATPKG}}
          ARTIFACT_VERSION: ${{env.artifact_version}}

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install dependencies
        run: mvn package -DskipTests

      # - name: Build with Maven
      #   run: mvn --batch-mode --update-snapshots verify
    #   - name: Run Formatter
    #     run: mvn com.coveo:fmt-maven-plugin:format
    #   - name: Test
    #     run: mvn test
