name: Maven CI/CD

on:
  push:
    branches: [ master ]
    paths:
      - gs-gmas-in-main/BancaSeguros/**


jobs:
  build_and_test:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            gs-gmas-in-main/BancaSeguros
    #   - name: Set up JDK 11
    #     uses: actions/setup-java@v2
    #     with:
    #       java-version: '11'
    #       distribution: 'adopt'
    #   - name: Install dependencies
    #     run: mvn package -DskipTests
    #   - name: Build with Maven
    #     run: mvn --batch-mode --update-snapshots verify
    #   - name: Run Formatter
    #     run: mvn com.coveo:fmt-maven-plugin:format
    #   - name: Test
    #     run: mvn test
