name: Publish package to GitHub Packages
run-name: "${{github.repository}} #${{github.run_id}} - Building ${{github.ref_name}} by @${{github.actor}}"

on:
  workflow_dispatch:  
  push:
    branches: 
      - develop
      - main

jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: npm i
      - run: npm run build
  
  publish:
    needs: build
    runs-on: self-hosted
    steps:
      - run: echo registry=https://npm.pkg.github.com/${{github.repository_owner}} >> .npmrc
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}