name: Publishing an API
run-name: "${{github.repository}} #${{github.run_number}} - Building ${{github.ref_name}} by @${{github.actor}}"

env:
  apim_id_dev: "/subscriptions/b80ae9bd-4aa9-4f1e-ae01-6a08372e16e9/resourceGroups/rg-dev-apim-eastus/providers/Microsoft.ApiManagement/service/apim-dev-gs/apis/"
  
  apim_id_prod: "/subscriptions/417aa725-413a-4317-81aa-a35c91a6400f/resourceGroups/rg-prd-apim-eastus/providers/Microsoft.ApiManagement/service/apim-prd-gs/apis/"

on:
  repository_dispatch:
    types: [apim-event]
    
jobs:
  apimEvent:
    runs-on: self-hosted
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
       
      - run: echo "${{ github.event.client_payload.openapi_url }}"
      - run: echo "${{ github.event.client_payload.prefix }}"
      - run: echo "${{ github.event.client_payload.api_id }}"
      - run: echo "${{ github.event.client_payload.environment }}"
      
      - name: Sleep 2 minutes until argocd synchronizes
        run: sleep 120s
        shell: bash
      
      - name: Set apim dev/testing/staging
        if: ${{ github.event.client_payload.environment == 'dev' || github.event.client_payload.environment == 'testing' || github.event.client_payload.environment == 'staging'}}
        run: |
          echo "api_id=${{ apim_id_dev }}/${{ github.event.client_payload.api_id }}" >> $GITHUB_ENV
          echo "apim_credential=${{ secrets.AZURE_APIM_CREDENTIAL_DEV }}" >> $GITHUB_ENV
      
      - name: Set apim prod
        if: ${{ github.event.client_payload.environment == 'prod' }}
        run: |
          echo "api_id=${{ apim_id_prod }}/${{ github.event.client_payload.api_id }}" >> $GITHUB_ENV
          echo "apim_credential=${{ secrets.AZURE_APIM_CREDENTIAL_PROD }}" >> $GITHUB_ENV
            
      - name: Update Azure API Management OpenAPI schema
        uses: OssiPesonen/action-update-api-management-openapi@master
        with:
          openAPIDefinitions: ${{ github.event.client_payload.openapi_url }}
          apiId: ${{ api_id }}
          apiUrlSuffix: ${{ github.event.client_payload.prefix }}
          credentials: ${{ apim_credential }}

      
          
      
            



