name: Repository Dispatch
on:
  repository_dispatch:
    types: [my-event]
jobs:
  myEvent:
    runs-on: self-hosted
    steps:
      - run: echo "${{ github.event.client_payload.repo }}"
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.client_payload.repo }}
          ref: ${{ github.event.client_payload.ref }}
          path: ${{ github.event.client_payload.repo }}
