name: Repository Dispatch
run-name: "${{github.repository}} #${{github.run_number}} - Building ${{github.ref_name}} by @${{github.actor}}"

on:
  repository_dispatch:
    types: [my-event]
jobs:
  myEvent:
    runs-on: self-hosted
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
       
      - run: echo "${{ github.event.client_payload.image }}"
      - run: echo "${{ github.event.client_payload.tag }}"
      - uses: actions/checkout@v4

      # - uses: actions/checkout@v4
        # with:
          # repository: ${{ github.event.client_payload.repo }}
          # ref: ${{ github.event.client_payload.ref }}
          # path: ${{ github.event.client_payload.repo }}
          
      - uses: ejhayes/action-argocd-deploy@releases/v1
        with:
          #accessToken: ${{ secrets.ARGOCD_TOKEN }}
          clientId: admin
          clientSecret: ${{ secrets.ARGOCD_ADMIN_PWD }}
          baseUrl: http://localhost:8888/
          clusterName: in-cluster
          name: testrepo
          namespace: marcelo
          project: default
          tokens: |
            REPLICAS: ${{ github.event.client_payload.replicas }}
            IMAGE: ${{ github.event.client_payload.image }}
            TAG: ${{ github.event.client_payload.tag }}
          path: charts/helm-testrepo
          valuesFile: charts/helm-testrepo/values.yaml
          info: |
            environment: dev
            
      # - name: Deploy
        # uses: cloudposse/github-action-deploy-argocd@main
        # id: deploy
        # with:
          # cluster: in-cluster
          # toolchain: helmfile
          # environment: preview
          # namespace: preview
          # application: test-app
          # #github-pat: ${{ secrets.GITHUB_AUTH_PAT }}
          # repository: ${{ github.repository }}
          # ref: ${{ github.event.pull_request.head.ref  }}
          # image: nginx
          # image-tag: latest
          # operation: deploy
          # debug: false
          # synchronously: true
